touch ./personality_primary_motivator.yaml
touch ./personality_emotional_disposition.yaml
touch ./personality_moodiness.yaml
touch ./personality_core_outlook.yaml
touch ./personality_core_integrity.yaml
touch ./personality_core_impulsiveness.yaml
touch ./personality_core_boldness.yaml
touch ./personality_core_flexibility.yaml
touch ./personality_core_affinity.yaml
touch ./personality_core_comportment.yaml
touch ./personality_core_interactivity.yaml
touch ./personality_core_sense of humor.yaml
touch ./personality_core_disclosure.yaml
touch ./personality_core_conformity.yaml
touch ./personality_sex_orientation.yaml
touch ./personality_sex_libido.yaml
touch ./personality_sex_expressiveness.yaml
touch ./personality_sex_expressive_style.yaml
touch ./personality_sex_openness.yaml
touch ./personality_sex_promiscuity.yaml
touch ./personality_religious_adherence.yaml
touch ./personality_religious_tolerance.yaml
touch ./personality_religious_expression.yaml
touch ./personality_religious_proselytizing.yaml
touch ./personality_religious_attitude.yaml
touch ./personality_conversation_topics.yaml
touch ./personality_quirks.yaml
touch ./personality_enjoyments.yaml
